#include "runtime/node_bootstrap_scripts.h"

namespace gode::node_bootstrap_scripts {

std::string commonjs_bootstrap_script() {
	return "const Module = require('module');"
		   "const path = require('path');"
		   "const fs = require('fs');"
		   "const gode = process._linkedBinding('godot');"
		   "const isGodotPath = p => typeof p === 'string' && (p.startsWith('res://') || p.startsWith('user://'));"
		   "const isRes = p => typeof p === 'string' && p.startsWith('res://');"
		   "const isUser = p => typeof p === 'string' && p.startsWith('user://');"
		   "const toPosix = p => {"
		   "    if (isRes(p)) return '/__gode_res__/' + p.substring(6);"
		   "    if (isUser(p)) return '/__gode_user__/' + p.substring(7);"
		   "    return p;"
		   "};"
		   "const fromPosix = p => {"
		   "    if (p === '/__gode_res__' || p === '/__gode_res__/') return 'res://';"
		   "    if (p === '/__gode_user__' || p === '/__gode_user__/') return 'user://';"
		   "    if (p.startsWith('/__gode_res__/')) return 'res://' + p.substring(14);"
		   "    if (p.startsWith('/__gode_user__/')) return 'user://' + p.substring(15);"
		   "    return p;"
		   "};"
		   "const tryExtensions = (p) => {"
		   "    const exts = ['.js', '.json', '.node', '.mjs', '.cjs'];"
		   "    for (const ext of exts) {"
		   "        if (fs.existsSync(p + ext)) return p + ext;"
		   "    }"
		   "    return null;"
		   "};"
		   "const resolveAsFileOrDirectory = (p) => {"
		   "    if (fs.existsSync(p) && fs.statSync(p).isFile()) return p;"
		   "    const withExt = tryExtensions(p);"
		   "    if (withExt) return withExt;"
		   "    if (fs.existsSync(p) && fs.statSync(p).isDirectory()) {"
		   "        const pkgPath = path.join(p, 'package.json');"
		   "        if (fs.existsSync(pkgPath)) {"
		   "            try {"
		   "                const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));"
		   "                if (pkg.main) {"
		   "                    const main = path.resolve(p, pkg.main);"
		   "                    if (fs.existsSync(main) && fs.statSync(main).isFile()) return main;"
		   "                    const mainExt = tryExtensions(main);"
		   "                    if (mainExt) return mainExt;"
		   "                    const mainIndex = path.join(main, 'index.js');"
		   "                    if (fs.existsSync(mainIndex)) return mainIndex;"
		   "                }"
		   "            } catch(e){}"
		   "        }"
		   "        const index = path.join(p, 'index.js');"
		   "        if (fs.existsSync(index)) return index;"
		   "    }"
		   "    return null;"
		   "};"
		   "const findInGodotPath = (base, req) => resolveAsFileOrDirectory(path.join(base, req));"
		   "try {"
		   "  const _gode_module = new Module('godot');"
		   "  _gode_module.id = 'godot';"
		   "  _gode_module.exports = gode;"
		   "  _gode_module.loaded = true;"
		   "  _gode_module.filename = 'godot';"
		   "  Module._cache['godot'] = _gode_module;"
		   "} catch (e) {"
		   "  console.error('[Gode] Injection error:', e);"
		   "}"
		   ""
		   "globalThis.__gode_open_inspector = function(port, host, wait, autoIncrementPort, maxPortRetries) {"
		   "  const inspector = require('inspector');"
		   "  const startPort = Number.isInteger(port) && port >= 0 && port <= 65535 ? port : 9229;"
		   "  const safeHost = typeof host === 'string' && host.length > 0 ? host : '127.0.0.1';"
		   "  const attempts = autoIncrementPort ? Math.max(1, Number(maxPortRetries) || 20) : 1;"
		   "  let lastError = null;"
		   "  for (let i = 0; i < attempts; i++) {"
		   "    const candidate = startPort === 0 ? 0 : startPort + i;"
		   "    if (candidate > 65535) break;"
		   "    try {"
		   "      inspector.open(candidate, safeHost, false);"
		   "      const url = inspector.url() || '';"
		   "      let resolvedPort = candidate;"
		   "      try {"
		   "        const parsedUrl = new URL(url);"
		   "        if (parsedUrl.port) resolvedPort = Number(parsedUrl.port);"
		   "      } catch (e) {}"
		   "      globalThis.__gode_inspector_url = url;"
		   "      return { ok: true, url, port: resolvedPort, error: '' };"
		   "    } catch (e) {"
		   "      lastError = e;"
		   "    }"
		   "  }"
		   "  const message = lastError && (lastError.stack || lastError.message) || 'Failed to open Node inspector';"
		   "  globalThis.__gode_inspector_error = message;"
		   "  return { ok: false, url: '', port: startPort, error: message };"
		   "};"
		   ""
		   "globalThis.__gode_wait_for_debugger = function() {"
		   "  try {"
		   "    require('inspector').waitForDebugger();"
		   "    return { ok: true, error: '' };"
		   "  } catch (e) {"
		   "    return { ok: false, error: e && (e.stack || e.message) || String(e) };"
		   "  }"
		   "};"
		   ""
		   "globalThis.__gode_close_inspector = function() {"
		   "  try {"
		   "    require('inspector').close();"
		   "    globalThis.__gode_inspector_url = '';"
		   "    return { ok: true, error: '' };"
		   "  } catch (e) {"
		   "    return { ok: false, error: e && (e.stack || e.message) || String(e) };"
		   "  }"
		   "};"
		   ""
		   "const originalReadFileSync = fs.readFileSync;"
		   "fs.readFileSync = function(p, options) {"
		   "  if (isGodotPath(p)) {"
		   "    const content = gode.fs_readFile(p);"
		   "    if (content !== null) return content;"
		   "  }"
		   "  return originalReadFileSync.call(fs, p, options);"
		   "};"
		   ""
		   "const originalExistsSync = fs.existsSync;"
		   "fs.existsSync = function(p) {"
		   "  if (isGodotPath(p)) {"
		   "    return gode.fs_stat(p) > 0;"
		   "  }"
		   "  return originalExistsSync ? originalExistsSync.call(fs, p) : false;"
		   "};"
		   ""
		   "const originalStatSync = fs.statSync;"
		   "fs.statSync = function(p, options) {"
		   "  if (isGodotPath(p)) {"
		   "    const type = gode.fs_stat(p);"
		   "    if (type > 0) {"
		   "      return {"
		   "        isDirectory: () => type === 2,"
		   "        isFile: () => type === 1,"
		   "        mtime: new Date(),"
		   "        size: 0"
		   "      };"
		   "    }"
		   "  }"
		   "  return originalStatSync.call(fs, p, options);"
		   "};"
		   ""
		   "const originalJoin = path.join;"
		   "const originalResolve = path.resolve;"
		   "const originalDirname = path.dirname;"
		   ""
		   "path.join = function(...args) {"
		   "  if (args.some(isGodotPath)) {"
		   "      const mapped = args.map(toPosix);"
		   "      return fromPosix(path.posix.join(...mapped));"
		   "  }"
		   "  return originalJoin.apply(path, args);"
		   "};"
		   ""
		   "path.resolve = function(...args) {"
		   "  if (args.some(isGodotPath)) {"
		   "      const mapped = args.map(toPosix);"
		   "      return fromPosix(path.posix.resolve(...mapped));"
		   "  }"
		   "  return originalResolve.apply(path, args);"
		   "};"
		   ""
		   "path.dirname = function(p) {"
		   "  if (isGodotPath(p)) {"
		   "      return fromPosix(path.posix.dirname(toPosix(p)));"
		   "  }"
		   "  return originalDirname.call(path, p);"
		   "};"
		   ""
		   "const originalNodeModulePaths = Module._nodeModulePaths;"
		   "Module._nodeModulePaths = function(from) {"
		   "    if (isGodotPath(from)) {"
		   "        const paths = [];"
		   "        let p = from;"
		   "        while (true) {"
		   "            paths.push(p + (p.endsWith('/') ? '' : '/') + 'node_modules');"
		   "            const parent = path.dirname(p);"
		   "            if (parent === p) break;"
		   "            if (p === 'res://' || p === 'user://') break;"
		   "            p = parent;"
		   "        }"
		   "        return paths;"
		   "    }"
		   "    return originalNodeModulePaths.call(Module, from);"
		   "};"
		   ""
		   "const originalFindPath = Module._findPath;"
		   "Module._findPath = function(request, paths, isMain) {"
		   "  if (isGodotPath(request)) {"
		   "      return request;"
		   "  }"
		   "  const godotPaths = paths.filter(isGodotPath);"
		   "  for (const base of godotPaths) {"
		   "      const found = findInGodotPath(base, request);"
		   "      if (found) return found;"
		   "  }"
		   "  return originalFindPath.call(Module, request, paths, isMain);"
		   "};"
		   ""
		   "const originalResolveFilename = Module._resolveFilename;"
		   "Module._resolveFilename = function(request, parent, isMain, options) {"
		   "  if (isGodotPath(request)) {"
		   "    return request;"
		   "  }"
		   "  if (parent && parent.filename && isGodotPath(parent.filename)) {"
		   "    if (request.startsWith('./') || request.startsWith('../')) {"
		   "      const parentDir = path.dirname(parent.filename);"
		   "      const base = path.resolve(parentDir, request);"
		   "      const found = resolveAsFileOrDirectory(base);"
		   "      return found || base;"
		   "    }"
		   "    try {"
		   "      return originalResolveFilename.call(Module, request, parent, isMain, options);"
		   "    } catch(e) {"
		   "      const found = findInGodotPath(path.join(path.dirname(parent.filename), 'node_modules'), request)"
		   "        || findInGodotPath('user://node_modules', request)"
		   "        || findInGodotPath('res://node_modules', request);"
		   "      if (found) return found;"
		   "      throw e;"
		   "    }"
		   "  }"
		   "  return originalResolveFilename.call(Module, request, parent, isMain, options);"
		   "};"
		   ""
		   "globalThis.__gode_compile = function(code, filename) {"
		   "  try {"
		   "    const m = new Module(filename, module);"
		   "    m.filename = filename;"
		   "    m.paths = Module._nodeModulePaths(path.dirname(filename));"
		   "    m._compile(code, filename);"
		   "    return m.exports;"
		   "  } catch (e) {"
		   "    console.error('Gode compile error:', e);"
		   "    return e;"
		   "  }"
		   "};"
		   "const originalRequire = Module.prototype.require;"
		   "Module.prototype.require = function(id) {"
		   "  if (id === 'godot') {"
		   "    return gode;"
		   "  }"
		   "  return originalRequire.call(this, id);"
		   "};"
		   "const originalGlobalRequire = globalThis.require || Module.createRequire(process.cwd());"
		   "globalThis.require = function(id) {"
		   ""
		   "  if (id === 'godot') {"
		   "    return gode;"
		   "  }"
		   "  return originalGlobalRequire.call(this, id);"
		   "};"
		   "if (originalGlobalRequire) Object.assign(globalThis.require, originalGlobalRequire);"
		   ""
		   // Patch process.dlopen: native .node modules must be loaded from real OS paths.
		   // Passing res:// paths to LoadLibraryW can produce invalid addresses and crash N-API initialization.
		   // Before loading .node, append its directory to PATH so Windows can find sibling DLLs such as ggml-cuda.dll.
		   "const _originalDlopen = process.dlopen;"
		   "process.dlopen = function(mod, filename, flags) {"
		   "  let realPath = filename;"
		   "  if (typeof filename === 'string') {"
		   "    let p = filename;"
		   "    if (p.startsWith('file://')) { try { p = require('url').fileURLToPath(p); } catch(_) {} }" // file:// → OS path
		   "    if (p.startsWith('res://')) { p = require('path').join(process.cwd(), p.slice(6)); }"
		   "    if (p.startsWith('\\\\\\\\?\\\\')) p = p.slice(4);" // Strip the \\?\ prefix.
		   "    realPath = p;"
		   "  }"
		   "  if (typeof realPath === 'string' && realPath.endsWith('.node') && typeof gode.preload_dlls === 'function') {"
		   "    try { gode.preload_dlls(require('path').dirname(realPath)); } catch(_) {}"
		   "  }"
		   "  return _originalDlopen(mod, realPath, flags);"
		   "};"
		   ""
		   "if (gode.GodotObject && gode.GodotObject.prototype) {"
		   "  gode.GodotObject.prototype.to_signal = function(signal, { timeoutMs, abortSignal } = {}) {"
		   "    const obj = this;"
		   "    return new Promise((resolve, reject) => {"
		   "      let done = false;"
		   "      let timer = null;"
		   "      const cleanup = () => {"
		   "        if (timer) clearTimeout(timer);"
		   "        if (abortSignal) abortSignal.removeEventListener('abort', onAbort);"
		   "        try { obj.disconnect(signal, callback); } catch (_) {}"
		   "      };"
		   "      const callback = (...args) => {"
		   "        if (done) return;"
		   "        done = true;"
		   "        cleanup();"
		   "        resolve(args.length <= 1 ? args[0] : args);"
		   "      };"
		   "      const onAbort = () => {"
		   "        if (done) return;"
		   "        done = true;"
		   "        cleanup();"
		   "        reject(new Error('to_signal: aborted'));"
		   "      };"
		   "      try {"
		   "        obj.connect(signal, callback);"
		   "      } catch (e) {"
		   "        cleanup();"
		   "        return reject(e);"
		   "      }"
		   "      if (abortSignal) abortSignal.addEventListener('abort', onAbort, { once: true });"
		   "      if (typeof timeoutMs === 'number' && timeoutMs > 0) {"
		   "        timer = setTimeout(() => {"
		   "          if (done) return;"
		   "          done = true;"
		   "          cleanup();"
		   "          reject(new Error(`to_signal: timeout waiting for '${signal}'`));"
		   "        }, timeoutMs);"
		   "      }"
		   "    });"
		   "  };"
		   "}"
		   ";"
		   "(function() {"
		   "  try {"
		   "    const compilerPath = 'res://addons/gode/runtime/typescript_compiler.js';"
		   "    const compilerSource = fs.readFileSync(compilerPath, 'utf8');"
		   "    const compiled = globalThis.__gode_compile(compilerSource, compilerPath);"
		   "    if (compiled instanceof Error) throw compiled;"
		   "  } catch(e) {"
		   "    globalThis.__gode_typescript_compiler_boot_error = e && (e.stack || e.message) || String(e);"
		   "  }"
		   "})()"
		   // Patch child_process.fork: intercept testBindingBinary forks and simulate success in-process.
		   // This avoids launching a GodotEngine.exe child process on Windows just for addon compatibility probes.
		   ";"
		   "(function() {"
		   "  try {"
		   "    const cp = require('child_process');"
		   "    const _origFork = cp.fork;"
		   "    cp.fork = function(modulePath, args, options) {"
		   "      if (typeof modulePath === 'string' && modulePath.includes('testBindingBinary')) {"
		   "        const { EventEmitter } = require('events');"
		   "        const mock = new EventEmitter();"
		   "        mock.pid = 0; mock.exitCode = null; mock.killed = false;"
		   "        mock.stdout = null; mock.stderr = null;"
		   "        mock.kill = function() {};"
		   "        mock.send = function(msg) {"
		   "          const self = this;"
		   "          if (msg && msg.type === 'start') {"
		   "            process.nextTick(() => self.emit('message', { type: 'loaded' }));"
		   "          } else if (msg && msg.type === 'test') {"
		   "            process.nextTick(() => self.emit('message', { type: 'done' }));"
		   "          } else if (msg && msg.type === 'exit') {"
		   "            process.nextTick(() => { mock.exitCode = 0; self.emit('exit', 0, null); });"
		   "          }"
		   "          return true;"
		   "        };"
		   "        process.nextTick(() => mock.emit('message', { type: 'ready' }));"
		   "        return mock;"
		   "      }"
		   "      return _origFork.apply(cp, arguments);"
		   "    };"
		   "  } catch(e) {}"
		   "})();";
}

std::string esm_bootstrap_script() {
	return "(function() {"
		   "const vm = require('vm');"
		   "const fs = require('fs');"
		   "const path = require('path');"
		   ""
		   "global.__gode_esm_supported = (typeof vm.SourceTextModule !== 'undefined');"
		   ""
		   "global.__gode_esm_cache = new Map();" // filepath -> namespace (fully evaluated)
		   "global.__gode_esm_pending = new Map();" // filepath -> Promise<namespace>
		   "global.__gode_esm_mod_cache = new Map();" // filepath/specifier -> vm.Module (for linker)
		   "global.__gode_esm_source_cache = new Map();" // filepath -> last successfully evaluated source
		   "global.__gode_esm_generation = 0;"
		   "global.__gode_cjs_pending = new Map();" // resolvedPath -> Promise<SyntheticModule> (dedup)
		   ""
		   // __gode_resolve_to_module resolves a specifier to a vm.Module.
		   // For ESM files, only create and return SourceTextModule; do not call link().
		   // Node's [kLink] machinery recursively invokes this linker asynchronously,
		   // avoiding synchronous recursion and stack overflows.
		   // Convert res:// paths to file:// URLs for import.meta.url.
		   // fileURLToPath() only accepts file:// URLs, so virtual paths must be converted.
		   "const _gode_is_virtual_path = (p) => typeof p === 'string' && (p.startsWith('res://') || p.startsWith('user://'));"
		   "const _gode_strip_module_generation = (p) => typeof p === 'string' ? p.replace(/\\?gode_gen=\\d+$/, '') : p;"
		   "const _gode_module_cache_key = (p) => String(global.__gode_esm_generation) + ':' + p;"
		   "const _gode_module_identifier = (p) => p + '?gode_gen=' + String(global.__gode_esm_generation);"
		   "const _gode_source_fallback = (p) => {"
		   "  if (typeof p !== 'string') return p;"
		   "  const cacheMarker = '/typescript-6.0.3/';"
		   "  if (p.startsWith('user://.gode/typescript/')) {"
		   "    const markerIndex = p.indexOf(cacheMarker);"
		   "    if (markerIndex >= 0) return 'res://' + p.slice(markerIndex + cacheMarker.length);"
		   "  }"
		   "  const exportPrefix = 'res://.gode/build/typescript/';"
		   "  if (p.startsWith(exportPrefix)) return 'res://' + p.slice(exportPrefix.length);"
		   "  return p;"
		   "};"
		   "const _gode_existing_or_source = (p) => {"
		   "  if (fs.existsSync(p)) return p;"
		   "  const fallback = _gode_source_fallback(p);"
		   "  return fallback !== p && fs.existsSync(fallback) ? fallback : p;"
		   "};"
		   "const _gode_virtual_to_file_url = (p) => {"
		   "  p = _gode_strip_module_generation(p);"
		   "  if (!p) return p;"
		   "  if (p.startsWith('file://')) return p;"
		   "  if (!p.startsWith('res://')) return require('url').pathToFileURL(p).href;"
		   "  const rel = p.slice(6);"
		   "  const abs = require('path').join(process.cwd(), rel).replace(/\\\\/g, '/');"
		   "  return require('url').pathToFileURL(abs).href;"
		   "};"
		   "const _gode_should_invalidate_require_cache = (p) => {"
		   "  if (typeof p !== 'string') return false;"
		   "  return _gode_is_virtual_path(p) || p.includes('/.gode/typescript/') || p.includes('\\\\.gode\\\\typescript\\\\');"
		   "};"
		   "global.__gode_invalidate_esm_module = function(filepath) {"
		   "  global.__gode_esm_cache.clear();"
		   "  global.__gode_esm_pending.clear();"
		   "  global.__gode_esm_source_cache.clear();"
		   "  global.__gode_esm_mod_cache.clear();"
		   "  global.__gode_esm_generation++;"
		   "  for (const key of Object.keys(require.cache)) {"
		   "    if (_gode_should_invalidate_require_cache(key)) delete require.cache[key];"
		   "  }"
		   "};"
		   ""
		   // Manually resolve package entries under res://node_modules/ when require.resolve cannot handle res:// paths.
		   "function __gode_resolve_in_res(specifier, referrerPath) {"
		   "  const parts = specifier.split('/');"
		   "  const pkgName = parts[0].startsWith('@') ? parts[0] + '/' + parts[1] : parts[0];"
		   "  const subPath = parts.slice(pkgName.split('/').length).join('/');"
		   "  let searchDirs = [];"
		   "  let d = path.dirname(referrerPath);"
		   "  while (true) {"
		   "    searchDirs.push(path.join(d, 'node_modules'));"
		   "    const p = path.dirname(d); if (p === d) break; d = p;"
		   "  }"
		   "  for (const base of searchDirs) {"
		   "    const pkgDir = path.join(base, pkgName);"
		   "    if (!fs.existsSync(pkgDir)) continue;"
		   "    if (subPath) {"
		   "      const direct = path.join(pkgDir, subPath);"
		   "      if (fs.existsSync(direct) && fs.statSync(direct).isFile()) return direct;"
		   "      for (const ext of ['.js', '.mjs', '.cjs', '.json']) {"
		   "        if (fs.existsSync(direct + ext)) return direct + ext;"
		   "      }"
		   "      return null;"
		   "    }"
		   "    const pkgJsonPath = path.join(pkgDir, 'package.json');"
		   "    if (!fs.existsSync(pkgJsonPath)) continue;"
		   "    let pkg; try { pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8')); } catch(_) { continue; }"
		   "    const exp = pkg.exports;"
		   "    if (exp) {"
		   "      const dot = exp['.'];"
		   "      const entry = typeof dot === 'string' ? dot"
		   "        : (dot && (dot.import || dot.module || dot.require || dot.default))"
		   "        || (typeof exp === 'string' ? exp : null);"
		   "      if (entry) { const r = path.resolve(pkgDir, entry); if (fs.existsSync(r)) return r; }"
		   "    }"
		   "    const main = pkg.module || pkg.main || 'index.js';"
		   "    const r = path.resolve(pkgDir, main);"
		   "    if (fs.existsSync(r)) return r;"
		   "    for (const ext of ['.js', '.mjs']) {"
		   "      if (fs.existsSync(r + ext)) return r + ext;"
		   "    }"
		   "  }"
		   "  return null;"
		   "}"
		   ""
		   // Resolve #subpath entries from package.json imports.
		   "function __gode_resolve_pkg_import(specifier, referrerPath) {"
		   "  let dir = path.dirname(referrerPath);"
		   "  while (true) {"
		   "    const pkgPath = path.join(dir, 'package.json');"
		   "    if (fs.existsSync(pkgPath)) {"
		   "      try {"
		   "        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));"
		   "        if (pkg.imports) {"
		   "          const entry = pkg.imports[specifier];"
		   "          if (entry) {"
		   "            const target = typeof entry === 'string' ? entry"
		   "              : (entry.node || entry.require || entry.default || null);"
		   "            if (target) return path.resolve(dir, target);"
		   "          }"
		   "        }"
		   "      } catch(_) {}"
		   "    }"
		   "    const parent = path.dirname(dir);"
		   "    if (parent === dir) break;"
		   "    dir = parent;"
		   "  }"
		   "  return null;"
		   "}"
		   ""
		   "global.__gode_resolve_to_module = async function(specifier, referrerPath) {"
		   "  referrerPath = _gode_strip_module_generation(referrerPath);"
		   "  let resolvedPath;"
		   "  if (specifier.startsWith('#')) {"
		   "    const pkgImport = __gode_resolve_pkg_import(specifier, referrerPath);"
		   "    if (!pkgImport) throw new Error(`Cannot find module '${specifier}' from '${referrerPath}'`);"
		   "    resolvedPath = pkgImport;"
		   "  } else if (specifier.startsWith('./') || specifier.startsWith('../')) {"
		   "    const dir = path.dirname(referrerPath);"
		   "    resolvedPath = path.resolve(dir, specifier);"
		   "    if (!fs.existsSync(resolvedPath)) {"
		   "      for (const ext of ['.mjs', '.js', '.cjs', '.json']) {"
		   "        if (fs.existsSync(resolvedPath + ext)) { resolvedPath = resolvedPath + ext; break; }"
		   "      }"
		   "    }"
		   "    resolvedPath = _gode_existing_or_source(resolvedPath);"
		   "  } else if (_gode_is_virtual_path(specifier)) {"
		   "    resolvedPath = _gode_existing_or_source(specifier);"
		   "  } else if (path.isAbsolute(specifier)) {"
		   "    resolvedPath = _gode_existing_or_source(specifier);"
		   "  } else if (specifier.startsWith('file://')) {"
		   "    resolvedPath = _gode_existing_or_source(require('url').fileURLToPath(specifier));"
		   "  } else {"
		   "    let _cjsMod; try { _cjsMod = require(specifier); } catch(_) {}"
		   "    if (_cjsMod !== undefined) {"
		   "      const cjsCacheKey = _gode_module_cache_key(specifier);"
		   "      if (global.__gode_esm_mod_cache.has(cjsCacheKey)) return global.__gode_esm_mod_cache.get(cjsCacheKey);"
		   "      const exportNames = Object.keys(_cjsMod);"
		   "      const names = exportNames.includes('default') ? exportNames : ['default', ...exportNames];"
		   "      const synMod = new vm.SyntheticModule(names, function() {"
		   "        this.setExport('default', _cjsMod);"
		   "        for (const key of exportNames) { this.setExport(key, _cjsMod[key]); }"
		   "      }, { identifier: _gode_module_identifier(specifier) });"
		   "      await synMod.link(() => {});"
		   "      await synMod.evaluate();"
		   "      global.__gode_esm_mod_cache.set(cjsCacheKey, synMod);"
		   "      return synMod;"
		   "    }"
		   "    try {"
		   "      resolvedPath = require.resolve(specifier, { paths: [path.dirname(referrerPath)] });"
		   "    } catch(e) {"
		   "      resolvedPath = __gode_resolve_in_res(specifier, referrerPath);"
		   "      if (!resolvedPath) {"
		   "        console.error('[gode] resolve failed: ' + specifier + ' from ' + referrerPath);"
		   "        throw new Error(`Cannot find module '${specifier}' from '${referrerPath}'`);"
		   "      }"
		   "    }"
		   "  }"
		   "  const cacheKey = _gode_module_cache_key(resolvedPath);"
		   "  if (global.__gode_esm_mod_cache.has(cacheKey)) {"
		   "    return global.__gode_esm_mod_cache.get(cacheKey);"
		   "  }"
		   "  let source;"
		   "  resolvedPath = _gode_existing_or_source(resolvedPath);"
		   "  try {"
		   "    source = fs.readFileSync(resolvedPath, 'utf8');"
		   "  } catch(e) {"
		   "    console.error('[gode] readFileSync failed: ' + resolvedPath + ' => ' + e.message);"
		   "    throw e;"
		   "  }"
		   "  const isESM = resolvedPath.endsWith('.mjs') ||"
		   "    (resolvedPath.endsWith('.js') && /^\\s*(import|export)\\s+/m.test(source));"
		   "  if (isESM) {"
		   "    let mod;"
		   "    try {"
		   "      mod = new vm.SourceTextModule(source, {"
		   "        identifier: _gode_module_identifier(resolvedPath),"
		   "        initializeImportMeta(meta) { meta.url = _gode_virtual_to_file_url(resolvedPath); },"
		   "        importModuleDynamically: async (spec, ref) => {"
		   "          return await global.__gode_import_module(spec, ref.identifier);"
		   "        }"
		   "      });"
		   "    } catch(e) {"
		   "      console.error('[gode] SourceTextModule parse error in ' + resolvedPath + ': ' + e.message);"
		   "      throw e;"
		   "    }"
		   "    global.__gode_esm_mod_cache.set(cacheKey, mod);"
		   "    return mod;"
		   "  } else {"
		   "    if (global.__gode_cjs_pending.has(resolvedPath)) return global.__gode_cjs_pending.get(resolvedPath);"
		   "    const cjsPromise = (async () => {"
		   "      try {"
		   "        let cjsModule;"
		   "        cjsModule = require(resolvedPath);"
		   "        const expNames = Object.keys(cjsModule);"
		   "        const allNames = expNames.includes('default') ? expNames : ['default', ...expNames];"
		   "        const synMod = new vm.SyntheticModule(allNames,"
		   "          function() {"
		   "            this.setExport('default', cjsModule);"
		   "            for (const key of expNames) { this.setExport(key, cjsModule[key]); }"
		   "          }, { identifier: _gode_module_identifier(resolvedPath) });"
		   "        await synMod.link(() => {});"
		   "        await synMod.evaluate();"
		   "        global.__gode_esm_mod_cache.set(cacheKey, synMod);"
		   "        return synMod;"
		   "      } catch(e) {"
		   "        console.error('[gode] CommonJS module load failed: ' + resolvedPath + ' => ' + e.message);"
		   "        throw e;"
		   "      } finally {"
		   "        global.__gode_cjs_pending.delete(resolvedPath);"
		   "      }"
		   "    })();"
		   "    global.__gode_cjs_pending.set(resolvedPath, cjsPromise);"
		   "    return cjsPromise;"
		   "  }"
		   "};"
		   ""
		   "global.__gode_import_module = async function(specifier, referrerPath) {"
		   "  const mod = await global.__gode_resolve_to_module(specifier, referrerPath);"
		   "  try {"
		   "    if (mod.status === 'unlinked') {"
		   "      await mod.link(async (nestedSpecifier, referencingModule) => {"
		   "        return await global.__gode_resolve_to_module(nestedSpecifier, referencingModule.identifier);"
		   "      });"
		   "    }"
		   "    if (mod.status === 'linked') {"
		   "      await mod.evaluate();"
		   "    }"
		   "    if (mod.status === 'errored') {"
		   "      throw mod.error || new Error('ESM module evaluation failed: ' + (mod.identifier || specifier));"
		   "    }"
		   "    return mod;"
		   "  } catch(e) {"
		   "    global.__gode_esm_mod_cache.clear();"
		   "    throw e;"
		   "  }"
		   "};"
		   ""
		   "global.__gode_load_esm = async function(filepath, source) {"
		   "  if (!global.__gode_esm_supported) {"
		   "    throw new Error('vm.SourceTextModule is not available');"
		   "  }"
		   "  if (global.__gode_esm_source_cache.has(filepath) && global.__gode_esm_source_cache.get(filepath) !== source) {"
		   "    global.__gode_invalidate_esm_module(filepath);"
		   "  }"
		   "  if (global.__gode_esm_cache.has(filepath)) { return global.__gode_esm_cache.get(filepath); }"
		   "  if (global.__gode_esm_pending.has(filepath)) { return global.__gode_esm_pending.get(filepath); }"
		   "  const loadPromise = (async () => {"
		   "    const module = new vm.SourceTextModule(source, {"
		   "      identifier: _gode_module_identifier(filepath),"
		   "      initializeImportMeta(meta) { meta.url = _gode_virtual_to_file_url(filepath); },"
		   "      importModuleDynamically: async (specifier, referrer) => {"
		   "        return await global.__gode_import_module(specifier, referrer.identifier);"
		   "      }"
		   "    });"
		   "    global.__gode_esm_mod_cache.set(_gode_module_cache_key(filepath), module);"
		   "    try {"
		   "      await module.link(async (specifier, referencingModule) => {"
		   "        return await global.__gode_resolve_to_module(specifier, referencingModule.identifier);"
		   "      });"
		   "    } catch(e) {"
		   "      console.error('[gode] link error in ' + filepath + ': ' + e.message);"
		   "      if (e.stack) console.error(e.stack);"
		   "      global.__gode_esm_mod_cache.clear();"
		   "      throw e;"
		   "    }"
		   "    try {"
		   "      await module.evaluate();"
		   "    } catch(e) {"
		   "      console.error('[gode] evaluate error in ' + filepath + ': ' + e.message);"
		   "      if (e.stack) console.error(e.stack);"
		   "      global.__gode_esm_mod_cache.clear();"
		   "      throw e;"
		   "    }"
		   "    const ns = module.namespace;"
		   "    global.__gode_esm_cache.set(filepath, ns);"
		   "    global.__gode_esm_source_cache.set(filepath, source);"
		   "    return ns;"
		   "  })().finally(() => {"
		   "    global.__gode_esm_pending.delete(filepath);"
		   "  });"
		   "  global.__gode_esm_pending.set(filepath, loadPromise);"
		   "  return loadPromise;"
		   "};"
		   ""
		   "global.__gode_compile_esm = async function(code, filename) {"
		   "  try {"
		   "    global.__gode_invalidate_esm_module(filename);"
		   "    const ns = await global.__gode_load_esm(filename, code);"
		   "    return ns;"
		   "  } catch (e) {"
		   "    console.error('[gode] compile_esm FAILED: ' + filename + ' => ' + (e && e.message));"
		   "    if (e && e.stack) console.error(e.stack);"
		   "    return e;"
		   "  }"
		   "};"
		   "})();";
}

} // namespace gode::node_bootstrap_scripts
